[package]
name = "event-sourcing-logstore-inmemory"
version = "0.1.0"
edition = "2021"

[dependencies]
event-sourcing = { path = "../event-sourcing" }
futures = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
futures = "0.3"
serde_json = "1"
