[package]
name = "event-sourcing"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
serde_json = { workspace = true }
thiserror = { workspace = true }
futures-core = { workspace = true }
indexmap = { workspace = true }
serde_json_path = { workspace = true }
async-trait = { workspace = true }
event-sourcing-macros = { path = "../event-sourcing-macros", optional = true }

[features]
macros = ["event-sourcing-macros"]

[dev-dependencies]
tokio = { version = "1", features = ["rt", "macros"] }
event-sourcing-logstore-inmemory = { path = "../event-sourcing-logstore-inmemory" }
futures = "0.3"
serde_json = { workspace = true }
